name: Print vars

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Print vars
        env:
          GLOBAL_SECRET: ${{ secrets.GLOBAL_SECRET }}
        run: |
          echo "The value is ${GLOBAL_SECRET:-global_secret}"
